title: Notes on Software Development
author:
  name: andrea-prearo
  email: andrea.prearo@gmail.com
description: >
  Yet another blog on Software Development ğŸ˜

markdown: kramdown
show_excerpts: false

theme: minima
minima:
  skin: solarized-dark
  social_links:
    github: andrea-prearo
    linkedin: andreaprearo

plugins:
  - jekyll-feed

include:
  - _about

exclude:
  - Gemfile
  - Gemfile.lock
